using System.Management.Automation;
using OfficeIMO.OpenDocument;
using PSWriteOffice.Services.OpenDocument;

namespace PSWriteOffice.Cmdlets.OpenDocument;

/// <summary>Adds a paragraph to an OpenDocument text document.</summary>
/// <example>
///   <summary>Add body text in the OpenDocument DSL.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficeOpenDocument -Kind Text -Path .\Report.odt -Content { Add-OfficeOpenDocumentParagraph -Text 'Generated by PSWriteOffice' }</code>
/// </example>
[Cmdlet(VerbsCommon.Add, "OfficeOpenDocumentParagraph")]
[OutputType(typeof(OdtParagraph))]
public sealed class AddOfficeOpenDocumentParagraphCommand : PSCmdlet {
    /// <summary>OpenDocument text document. Omit inside New-OfficeOpenDocument -Content.</summary>
    [Parameter(ValueFromPipeline = true)]
    public OdtDocument? Document { get; set; }

    /// <summary>Paragraph text.</summary>
    [Parameter(Mandatory = true, Position = 0)]
    public string Text { get; set; } = string.Empty;

    /// <summary>Emit the created paragraph.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <inheritdoc />
    protected override void ProcessRecord() {
        OdtDocument document = Document ?? OpenDocumentDslContext.Require(this).RequireDocument<OdtDocument>(this, "text");
        OdtParagraph paragraph = document.AddParagraph(Text);
        if (PassThru.IsPresent) WriteObject(paragraph);
    }
}
