using System.IO;
using System.Management.Automation;
using OfficeIMO.OpenDocument;
using PSWriteOffice.Services.OpenDocument;

namespace PSWriteOffice.Cmdlets.OpenDocument;

/// <summary>Creates a native ODT, ODS, or ODP document.</summary>
/// <example>
///   <summary>Create an OpenDocument text report.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficeOpenDocument -Kind Text -Path .\Report.odt -Content {
///     Add-OfficeOpenDocumentHeading -Text 'Service report' -Level 1
///     Add-OfficeOpenDocumentParagraph -Text 'Generated by PSWriteOffice.'
/// }</code>
/// </example>
/// <example>
///   <summary>Create a spreadsheet with typed cells.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficeOpenDocument -Kind Spreadsheet -Path .\Status.ods -Content {
///     Add-OfficeOpenDocumentSheet -Name 'Services' -Content {
///         Set-OfficeOpenDocumentCell -Row 0 -Column 0 -Value 'Service'
///         Set-OfficeOpenDocumentCell -Row 0 -Column 1 -Value 'Healthy'
///         Set-OfficeOpenDocumentCell -Row 1 -Column 0 -Value 'Directory'
///         Set-OfficeOpenDocumentCell -Row 1 -Column 1 -Value $true
///     }
/// }</code>
/// </example>
[Cmdlet(VerbsCommon.New, "OfficeOpenDocument", SupportsShouldProcess = true)]
[Alias("OfficeOpenDocument", "OpenDocumentNew")]
[OutputType(typeof(OdfDocument), typeof(FileInfo))]
public sealed class NewOfficeOpenDocumentCommand : PSCmdlet {
    /// <summary>OpenDocument text, spreadsheet, or presentation kind.</summary>
    [Parameter(Mandatory = true, Position = 0)]
    public OdfDocumentKind Kind { get; set; }

    /// <summary>Optional initial destination path.</summary>
    [Parameter(Position = 1)]
    public string? Path { get; set; }

    /// <summary>DSL scriptblock describing OpenDocument text, spreadsheet, or presentation content.</summary>
    [Parameter(Position = 2)]
    public ScriptBlock? Content { get; set; }

    /// <summary>Skip saving and emit the live OpenDocument model even when -Path is supplied.</summary>
    [Parameter]
    public SwitchParameter NoSave { get; set; }

    /// <summary>Emit the saved file when a destination path is supplied.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <inheritdoc />
    protected override void ProcessRecord() {
        string? path = null;
        bool save = !string.IsNullOrWhiteSpace(Path) && !NoSave.IsPresent;
        if (save) {
            path = SessionState.Path.GetUnresolvedProviderPathFromPSPath(Path!);
            OpenDocumentCommandUtilities.ValidateOpenDocumentExtension(path, Kind, nameof(Path));
            if (!ShouldProcess(path, "Create OpenDocument package")) {
                return;
            }
        }

        OdfDocument document = Kind switch {
            OdfDocumentKind.Text => OdtDocument.Create(),
            OdfDocumentKind.Spreadsheet => OdsDocument.Create(),
            OdfDocumentKind.Presentation => OdpPresentation.Create(),
            _ => throw new PSArgumentOutOfRangeException(nameof(Kind), Kind, "Use Text, Spreadsheet, or Presentation.")
        };
        if (Content != null) {
            using (OpenDocumentDslContext.Enter(document)) {
                Content.InvokeReturnAsIs();
            }
        }

        if (save) {
            Directory.CreateDirectory(System.IO.Path.GetDirectoryName(path!) ?? SessionState.Path.CurrentFileSystemLocation.Path);
            document.Save(path!);
            if (PassThru.IsPresent) {
                WriteObject(new FileInfo(path!));
            }
            return;
        }
        WriteObject(document);
    }
}
