using System;
using System.IO;
using System.Management.Automation;
using System.Text;
using OfficeIMO.Html;
using OfficeIMO.Html.Pdf;
using PSWriteOffice.Services;
using PSWriteOffice.Services.Pdf;

namespace PSWriteOffice.Cmdlets.Pdf;

/// <summary>Converts HTML content to a PDF through the first-party OfficeIMO HTML/PDF adapter.</summary>
/// <example>
///   <summary>Create a PDF from an HTML fragment.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>$html = '&lt;h1&gt;Report&lt;/h1&gt;&lt;p&gt;Ready&lt;/p&gt;'
/// ConvertFrom-OfficePdfHtml -Html $html -OutputPath .\report.pdf -PassThru</code>
///   <para>Writes a PDF generated by OfficeIMO.Html.Pdf.</para>
/// </example>
[Cmdlet(VerbsData.ConvertFrom, "OfficePdfHtml", DefaultParameterSetName = ParameterSetHtml, SupportsShouldProcess = true)]
[Alias("ConvertFrom-PdfHtml")]
[OutputType(typeof(byte[]), typeof(FileInfo))]
public sealed class ConvertFromOfficePdfHtmlCommand : PSCmdlet
{
    private const string ParameterSetHtml = "Html";
    private const string ParameterSetPath = "Path";
    private readonly StringBuilder _pipelineHtml = new();
    private bool _receivedHtml;

    /// <summary>HTML markup to convert.</summary>
    [Parameter(Mandatory = true, Position = 0, ValueFromPipeline = true, ParameterSetName = ParameterSetHtml)]
    public string Html { get; set; } = string.Empty;

    /// <summary>Path to an HTML file.</summary>
    [Parameter(Mandatory = true, ParameterSetName = ParameterSetPath)]
    [Alias("FilePath", "Path")]
    public string InputPath { get; set; } = string.Empty;

    /// <summary>Optional output path for the PDF file. When omitted, PDF bytes are written to the pipeline.</summary>
    [Parameter]
    [Alias("OutPath")]
    public string? OutputPath { get; set; }

    /// <summary>HTML conversion profile applied before PDF rendering.</summary>
    [Parameter]
    public HtmlConversionProfile Profile { get; set; } = HtmlConversionProfile.Semantic;

    /// <summary>Mark the HTML input as trusted for OfficeIMO conversion policy.</summary>
    [Parameter]
    public SwitchParameter TrustedDocumentProfile { get; set; }

    /// <summary>Base path used to resolve relative file resources.</summary>
    [Parameter]
    public string? BasePath { get; set; }

    /// <summary>Paths to CSS stylesheets to apply when using the document profile.</summary>
    [Parameter]
    public string[]? StylesheetPath { get; set; }

    /// <summary>Inline CSS stylesheets to apply when using the document profile.</summary>
    [Parameter]
    public string[]? StylesheetContent { get; set; }

    /// <summary>Optional OfficeIMO HTML to PDF save options.</summary>
    [Parameter]
    public HtmlPdfSaveOptions? Options { get; set; }

    /// <summary>Open the PDF after saving.</summary>
    [Parameter]
    public SwitchParameter Open { get; set; }

    /// <summary>Emit a <see cref="FileInfo"/> when saving to disk.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <inheritdoc />
    protected override void ProcessRecord()
    {
        try
        {
            if (ParameterSetName == ParameterSetHtml)
            {
                if (_receivedHtml)
                {
                    _pipelineHtml.AppendLine();
                }

                _pipelineHtml.Append(Html);
                _receivedHtml = true;
                return;
            }

            string resolvedPath = PdfCommandUtilities.ResolvePath(this, InputPath);
            if (!File.Exists(resolvedPath))
            {
                throw new FileNotFoundException($"File '{resolvedPath}' was not found.", resolvedPath);
            }

            ConvertHtml(File.ReadAllText(resolvedPath), Path.GetDirectoryName(resolvedPath));
        }
        catch (Exception ex)
        {
            WriteError(new ErrorRecord(ex, "HtmlToPdfFailed", ErrorCategory.InvalidOperation,
                ParameterSetName == ParameterSetPath ? InputPath : Html));
        }
    }

    /// <inheritdoc />
    protected override void EndProcessing()
    {
        if (ParameterSetName != ParameterSetHtml || !_receivedHtml)
        {
            return;
        }

        try
        {
            ConvertHtml(_pipelineHtml.ToString(), htmlFileDirectory: null);
        }
        catch (Exception ex)
        {
            WriteError(new ErrorRecord(ex, "HtmlToPdfFailed", ErrorCategory.InvalidOperation, Html));
        }
    }

    private void ConvertHtml(string html, string? htmlFileDirectory)
    {
        if (string.IsNullOrWhiteSpace(html))
        {
            ThrowTerminatingError(new ErrorRecord(
                new ArgumentException("HTML content cannot be empty."),
                "HtmlEmpty",
                ErrorCategory.InvalidArgument,
                html));
            return;
        }

        string preparedHtml = ApplyStylesheets(html);
        HtmlPdfSaveOptions options = BuildOptions(htmlFileDirectory);
        HtmlConversionDocument document = HtmlConversionDocument.Parse(preparedHtml, new HtmlConversionDocumentOptions
        {
            Profile = Profile,
            Trust = TrustedDocumentProfile.IsPresent ? HtmlInputTrust.Trusted : HtmlInputTrust.Untrusted,
            BaseUri = options.BaseUri
        });
        if (!string.IsNullOrWhiteSpace(OutputPath))
        {
            string outputPath = PdfCommandUtilities.ResolvePath(this, OutputPath!);
            if (!PdfCommandUtilities.ShouldWrite(this, outputPath, "Write PDF from HTML"))
            {
                return;
            }

            PdfCommandUtilities.EnsureDirectory(outputPath);
            document.SaveAsPdf(outputPath, options);
            if (Open.IsPresent)
            {
                FileOpenService.Open(outputPath);
            }

            if (PassThru.IsPresent)
            {
                WriteObject(new FileInfo(outputPath));
            }

            return;
        }

        WriteObject(document.ToPdf(options), enumerateCollection: false);
    }

    private HtmlPdfSaveOptions BuildOptions(string? htmlFileDirectory)
    {
        HtmlPdfSaveOptions options = Options?.ClonePdf() ?? new HtmlPdfSaveOptions();

        ApplyResourceOptions(options, htmlFileDirectory);
        return options;
    }

    private void ApplyResourceOptions(HtmlPdfSaveOptions options, string? htmlFileDirectory)
    {
        string? resolvedBasePath = null;
        if (!string.IsNullOrWhiteSpace(BasePath))
        {
            resolvedBasePath = PdfCommandUtilities.ResolvePath(this, BasePath!);
        }
        else if (!string.IsNullOrWhiteSpace(htmlFileDirectory))
        {
            resolvedBasePath = htmlFileDirectory;
        }

        if (!string.IsNullOrWhiteSpace(resolvedBasePath))
        {
            options.BaseUri = new Uri(Path.GetFullPath(resolvedBasePath!) + Path.DirectorySeparatorChar);
        }
    }

    private string ApplyStylesheets(string html)
    {
        var styles = new StringBuilder();

        if (StylesheetPath != null)
        {
            foreach (string path in StylesheetPath)
            {
                if (!string.IsNullOrWhiteSpace(path))
                {
                    string resolvedPath = PdfCommandUtilities.ResolvePath(this, path);
                    if (!File.Exists(resolvedPath))
                    {
                        throw new FileNotFoundException($"Stylesheet file '{resolvedPath}' was not found.", resolvedPath);
                    }

                    styles.AppendLine(File.ReadAllText(resolvedPath));
                }
            }
        }

        if (StylesheetContent != null)
        {
            foreach (string content in StylesheetContent)
            {
                if (!string.IsNullOrWhiteSpace(content))
                {
                    styles.AppendLine(content);
                }
            }
        }

        return styles.Length == 0
            ? html
            : "<style>" + Environment.NewLine + styles + "</style>" + Environment.NewLine + html;
    }
}
