using System.IO;
using System.Management.Automation;
using OfficeIMO.Pdf;
using PSWriteOffice.Services;
using PSWriteOffice.Services.Pdf;

namespace PSWriteOffice.Cmdlets.Pdf;

/// <summary>Creates a PDF document using the OfficeIMO.Pdf composition engine.</summary>
/// <remarks>
/// <c>New-OfficePdf</c> starts a generated PDF document and optionally executes a PSWriteOffice PDF DSL script block.
/// The DSL commands are thin adapters over OfficeIMO.Pdf and support document metadata, page setup, headers, footers,
/// themes, styled text, tables, panels, row layouts, form fields, attachments, compliance settings, and save/open behavior.
/// Use <c>-NoSave</c> or omit <c>-Path</c> when a document object should be returned for further pipeline operations.
/// </remarks>
/// <example>
///   <summary>Create a PDF report.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficePdf -Path .\Report.pdf { PdfHeading 'Report'; PdfParagraph 'Generated by PSWriteOffice' } -Show</code>
///   <para>Builds a PDF and opens it after saving.</para>
/// </example>
/// <example>
///   <summary>Create a polished report with theme, metadata, and layout.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficePdf -Path .\ServiceReview.pdf {
///     PdfTheme Report
///     PdfMetadata -Title 'Service Review' -Author 'PSWriteOffice'
///     PdfPageSetup -PageSize A4 -Margin 42
///     PdfHeader 'Service Review'
///     PdfFooter 'Page {page}/{pages}'
///     PdfHeading 'Service Review'
///     PdfText -Run @(
///       @{ Text = 'Generated with ' }
///       @{ Text = 'rich inline text'; Bold = $true; Color = '#0F766E' }
///       @{ Text = ' and OfficeIMO.Pdf layout.' }
///     )
///     PdfRow -Column @(
///       @{ Width = 40; Content = @(@{ Type = 'Panel'; Text = 'Left summary' }) }
///       @{ Width = 60; Content = @(@{ Type = 'Paragraph'; Text = 'Right details' }) }
///     )
///   }</code>
///   <para>Shows the preferred high-level PDF report authoring shape.</para>
/// </example>
[Cmdlet(VerbsCommon.New, "OfficePdf", DefaultParameterSetName = ParameterSetPath)]
[OutputType(typeof(PdfDocument), typeof(FileInfo))]
public sealed class NewOfficePdfCommand : PSCmdlet
{
    private const string ParameterSetPath = "Path";
    private const string ParameterSetContent = "Content";

    /// <summary>Optional destination PDF path.</summary>
    [Parameter(Position = 0, ParameterSetName = ParameterSetPath)]
    [Alias("FilePath")]
    public string? Path { get; set; }

    /// <summary>DSL script block describing generated PDF content.</summary>
    [Parameter(Position = 1, ParameterSetName = ParameterSetPath)]
    [Parameter(Position = 0, ParameterSetName = ParameterSetContent)]
    public ScriptBlock? Content { get; set; }

    /// <summary>Emit the generated document or saved file for chaining.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <summary>Skip saving even when -Path is provided.</summary>
    [Parameter]
    public SwitchParameter NoSave { get; set; }

    /// <summary>Open the PDF after saving.</summary>
    [Parameter]
    public SwitchParameter Show { get; set; }

    /// <summary>Default standard PDF font for generated text.</summary>
    [Parameter]
    public PdfStandardFont? DefaultFont { get; set; }

    /// <summary>Default generated text font size in points.</summary>
    [Parameter]
    public double? DefaultFontSize { get; set; }

    /// <summary>Embedded TrueType font family name for generated text.</summary>
    [Parameter]
    public string? FontFamily { get; set; }

    /// <summary>Regular TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    [Alias("FontPath")]
    public string? RegularFontPath { get; set; }

    /// <summary>Optional bold TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? BoldFontPath { get; set; }

    /// <summary>Optional italic TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? ItalicFontPath { get; set; }

    /// <summary>Optional bold italic TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? BoldItalicFontPath { get; set; }

    /// <inheritdoc />
    protected override void ProcessRecord()
    {
        var document = PdfDocument.Create(CreateOptions());
        if (Content != null)
        {
            using (PdfDslContext.Enter(document))
            {
                Content.InvokeReturnAsIs();
            }
        }

        if (string.IsNullOrWhiteSpace(Path) || NoSave.IsPresent)
        {
            WriteObject(document);
            return;
        }

        var fullPath = PdfCommandUtilities.ResolvePath(this, Path!);
        PdfCommandUtilities.EnsureDirectory(fullPath);
        document.Save(fullPath);

        if (Show.IsPresent)
        {
            FileOpenService.Open(fullPath);
        }

        if (PassThru.IsPresent)
        {
            WriteObject(new FileInfo(fullPath));
        }
    }

    private PdfOptions CreateOptions()
    {
        var options = new PdfOptions();
        if (DefaultFont.HasValue)
        {
            options.DefaultFont = DefaultFont.Value;
        }

        if (DefaultFontSize.HasValue)
        {
            options.DefaultFontSize = DefaultFontSize.Value;
        }

        if (!string.IsNullOrWhiteSpace(FontFamily))
        {
            if (string.IsNullOrWhiteSpace(RegularFontPath))
            {
                throw new PSArgumentException("-FontFamily requires -RegularFontPath.", nameof(RegularFontPath));
            }

            options.UseFontFamily(
                FontFamily!,
                PdfCommandUtilities.ResolvePath(this, RegularFontPath!),
                ResolveOptionalFontPath(BoldFontPath),
                ResolveOptionalFontPath(ItalicFontPath),
                ResolveOptionalFontPath(BoldItalicFontPath));
        }

        return options;
    }

    private string? ResolveOptionalFontPath(string? path)
    {
        return string.IsNullOrWhiteSpace(path)
            ? null
            : PdfCommandUtilities.ResolvePath(this, path!);
    }
}
