using System.IO;
using System.Management.Automation;
using OfficeIMO.Pdf;
using PSWriteOffice.Services;
using PSWriteOffice.Services.Pdf;

namespace PSWriteOffice.Cmdlets.Pdf;

/// <summary>Creates a PDF document using the OfficeIMO.Pdf composition engine.</summary>
/// <remarks>
/// <c>New-OfficePdf</c> starts a generated PDF document and optionally executes a PSWriteOffice PDF DSL script block.
/// The DSL commands are thin adapters over OfficeIMO.Pdf and support document metadata, page setup, headers, footers,
/// themes, styled text, tables, panels, row layouts, form fields, attachments, compliance settings, and save/open behavior.
/// Use <c>-NoSave</c> or omit <c>-Path</c> when a document object should be returned for further pipeline operations.
/// </remarks>
/// <example>
///   <summary>Create a PDF report.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficePdf -Path .\Report.pdf { PdfHeading 'Report'; PdfParagraph 'Generated by PSWriteOffice' } -Show</code>
///   <para>Builds a PDF and opens it after saving.</para>
/// </example>
/// <example>
///   <summary>Create a polished report with theme, metadata, and layout.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficePdf -Path .\ServiceReview.pdf {
///     PdfTheme Report
///     PdfMetadata -Title 'Service Review' -Author 'PSWriteOffice'
///     PdfPageSetup -PageSize A4 -Margin 42
///     PdfHeader 'Service Review'
///     PdfFooter 'Page {page}/{pages}'
///     PdfHeading 'Service Review'
///     PdfText -Run @(
///       @{ Text = 'Generated with ' }
///       @{ Text = 'rich inline text'; Bold = $true; Color = '#0F766E' }
///       @{ Text = ' and OfficeIMO.Pdf layout.' }
///     )
///     PdfRow -Column @(
///       @{ Width = 40; Content = @(@{ Type = 'Panel'; Text = 'Left summary' }) }
///       @{ Width = 60; Content = @(@{ Type = 'Paragraph'; Text = 'Right details' }) }
///     )
///   }</code>
///   <para>Shows the preferred high-level PDF report authoring shape.</para>
/// </example>
[Cmdlet(VerbsCommon.New, "OfficePdf", DefaultParameterSetName = ParameterSetPath)]
[OutputType(typeof(PdfDocument), typeof(FileInfo))]
public sealed class NewOfficePdfCommand : PSCmdlet
{
    private const string ParameterSetPath = "Path";
    private const string ParameterSetContent = "Content";

    /// <summary>Optional destination PDF path.</summary>
    [Parameter(Position = 0, ParameterSetName = ParameterSetPath)]
    [Alias("FilePath")]
    public string? Path { get; set; }

    /// <summary>DSL script block describing generated PDF content.</summary>
    [Parameter(Position = 1, ParameterSetName = ParameterSetPath)]
    [Parameter(Position = 0, ParameterSetName = ParameterSetContent)]
    public ScriptBlock? Content { get; set; }

    /// <summary>Emit the generated document or saved file for chaining.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <summary>Skip saving even when -Path is provided.</summary>
    [Parameter]
    public SwitchParameter NoSave { get; set; }

    /// <summary>Open the PDF after saving.</summary>
    [Parameter]
    public SwitchParameter Show { get; set; }

    /// <summary>Default standard PDF font for generated text.</summary>
    [Parameter]
    public PdfStandardFont? DefaultFont { get; set; }

    /// <summary>Default generated text font size in points.</summary>
    [Parameter]
    public double? DefaultFontSize { get; set; }

    /// <summary>Built-in OfficeIMO.Pdf theme applied before the DSL content runs.</summary>
    [Parameter]
    public OfficePdfThemePreset? Theme { get; set; }

    /// <summary>Embedded TrueType font family name for generated text.</summary>
    [Parameter]
    public string? FontFamily { get; set; }

    /// <summary>Regular TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    [Alias("FontPath")]
    public string? RegularFontPath { get; set; }

    /// <summary>Optional bold TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? BoldFontPath { get; set; }

    /// <summary>Optional italic TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? ItalicFontPath { get; set; }

    /// <summary>Optional bold italic TrueType font path used when -FontFamily is provided.</summary>
    [Parameter]
    public string? BoldItalicFontPath { get; set; }

    /// <summary>PDF file header version emitted by OfficeIMO.Pdf.</summary>
    [Parameter]
    public PdfFileVersion? FileVersion { get; set; }

    /// <summary>Create PDF outline/bookmark entries from heading elements.</summary>
    [Parameter]
    public SwitchParameter CreateOutlineFromHeadings { get; set; }

    /// <summary>Initial outline expansion level when heading outlines are created.</summary>
    [Parameter]
    public int? OutlineExpansionLevel { get; set; }

    /// <summary>Catalog page mode hint emitted for generated PDFs.</summary>
    [Parameter]
    public PdfCatalogPageMode? PageMode { get; set; }

    /// <summary>Catalog page layout hint emitted for generated PDFs.</summary>
    [Parameter]
    public PdfCatalogPageLayout? PageLayout { get; set; }

    /// <summary>Emit generated catalog page labels.</summary>
    [Parameter]
    public SwitchParameter IncludePageLabels { get; set; }

    /// <summary>Optional generated page-label prefix.</summary>
    [Parameter]
    public string? PageLabelPrefix { get; set; }

    /// <summary>Initial one-based page shown by PDF viewers that honor open actions.</summary>
    [Parameter]
    public int? OpenActionPage { get; set; }

    /// <summary>Open-action destination mode.</summary>
    [Parameter]
    public PdfOpenActionDestinationMode? OpenActionMode { get; set; }

    /// <summary>Optional open-action top coordinate.</summary>
    [Parameter]
    public double? OpenActionTop { get; set; }

    /// <summary>Request PDF viewers to display the document title instead of the file name.</summary>
    [Parameter]
    public SwitchParameter DisplayDocTitle { get; set; }

    /// <summary>Request PDF viewers to fit the document window to the first displayed page.</summary>
    [Parameter]
    public SwitchParameter FitWindow { get; set; }

    /// <summary>Request PDF viewers to center the document window on screen.</summary>
    [Parameter]
    public SwitchParameter CenterWindow { get; set; }

    /// <summary>Request PDF viewers to hide the toolbar.</summary>
    [Parameter]
    public SwitchParameter HideToolbar { get; set; }

    /// <summary>Request PDF viewers to hide the menu bar.</summary>
    [Parameter]
    public SwitchParameter HideMenubar { get; set; }

    /// <summary>Request PDF viewers to hide user-interface elements.</summary>
    [Parameter]
    public SwitchParameter HideWindowUI { get; set; }

    /// <summary>Flatten generated FreeText and Highlight annotations into static page content.</summary>
    [Parameter]
    public SwitchParameter FlattenVisualAnnotations { get; set; }

    /// <summary>Password required to open the generated PDF.</summary>
    [Parameter]
    [Alias("UserPassword")]
    public string? Password { get; set; }

    /// <summary>Optional owner password for the generated encrypted PDF.</summary>
    [Parameter]
    public string? OwnerPassword { get; set; }

    /// <summary>Raw PDF Standard security permission bit mask. Defaults to allowing all standard operations.</summary>
    [Parameter]
    [Alias("Permissions")]
    public int? Permission { get; set; }

    /// <inheritdoc />
    protected override void ProcessRecord()
    {
        var document = PdfDocument.Create(CreateOptions());
        if (Content != null)
        {
            using (PdfDslContext.Enter(document))
            {
                Content.InvokeReturnAsIs();
            }
        }

        if (string.IsNullOrWhiteSpace(Path) || NoSave.IsPresent)
        {
            WriteObject(document);
            return;
        }

        var fullPath = PdfCommandUtilities.ResolvePath(this, Path!);
        PdfCommandUtilities.EnsureDirectory(fullPath);
        document.Save(fullPath);

        if (Show.IsPresent)
        {
            FileOpenService.Open(fullPath);
        }

        if (PassThru.IsPresent)
        {
            WriteObject(new FileInfo(fullPath));
        }
    }

    private PdfOptions CreateOptions()
    {
        var options = new PdfOptions();
        if (DefaultFont.HasValue)
        {
            options.DefaultFont = DefaultFont.Value;
        }

        if (DefaultFontSize.HasValue)
        {
            options.DefaultFontSize = DefaultFontSize.Value;
        }

        if (Theme.HasValue)
        {
            options.ApplyTheme(PdfThemeUtilities.ResolveTheme(Theme.Value));
        }

        if (FileVersion.HasValue)
        {
            options.FileVersion = FileVersion.Value;
        }

        if (CreateOutlineFromHeadings.IsPresent)
        {
            options.CreateOutlineFromHeadings = true;
        }

        if (OutlineExpansionLevel.HasValue)
        {
            options.OutlineExpansionLevel = OutlineExpansionLevel.Value;
        }

        if (PageMode.HasValue || PageLayout.HasValue)
        {
            options.SetCatalogView(PageMode, PageLayout);
        }

        if (IncludePageLabels.IsPresent || !string.IsNullOrWhiteSpace(PageLabelPrefix))
        {
            options.SetPageLabels(true, PageLabelPrefix);
        }

        if (OpenActionPage.HasValue || OpenActionMode.HasValue || OpenActionTop.HasValue)
        {
            options.SetOpenAction(
                OpenActionPage ?? 1,
                OpenActionTop,
                OpenActionMode ?? PdfOpenActionDestinationMode.Xyz);
        }

        if (FlattenVisualAnnotations.IsPresent)
        {
            options.SetFlattenVisualAnnotations();
        }

        ConfigureViewerPreferences(options);
        PdfCommandUtilities.ApplyEncryption(options, Password, OwnerPassword, Permission);

        if (!string.IsNullOrWhiteSpace(FontFamily))
        {
            if (string.IsNullOrWhiteSpace(RegularFontPath))
            {
                throw new PSArgumentException("-FontFamily requires -RegularFontPath.", nameof(RegularFontPath));
            }

            options.UseFontFamily(
                FontFamily!,
                PdfCommandUtilities.ResolvePath(this, RegularFontPath!),
                ResolveOptionalFontPath(BoldFontPath),
                ResolveOptionalFontPath(ItalicFontPath),
                ResolveOptionalFontPath(BoldItalicFontPath));
        }

        return options;
    }

    private void ConfigureViewerPreferences(PdfOptions options)
    {
        if (!DisplayDocTitle.IsPresent &&
            !FitWindow.IsPresent &&
            !CenterWindow.IsPresent &&
            !HideToolbar.IsPresent &&
            !HideMenubar.IsPresent &&
            !HideWindowUI.IsPresent)
        {
            return;
        }

        options.ConfigureViewerPreferences(preferences =>
        {
            if (DisplayDocTitle.IsPresent)
            {
                preferences.DisplayDocTitle = true;
            }

            if (FitWindow.IsPresent)
            {
                preferences.FitWindow = true;
            }

            if (CenterWindow.IsPresent)
            {
                preferences.CenterWindow = true;
            }

            if (HideToolbar.IsPresent)
            {
                preferences.HideToolbar = true;
            }

            if (HideMenubar.IsPresent)
            {
                preferences.HideMenubar = true;
            }

            if (HideWindowUI.IsPresent)
            {
                preferences.HideWindowUI = true;
            }
        });
    }

    private string? ResolveOptionalFontPath(string? path)
    {
        return string.IsNullOrWhiteSpace(path)
            ? null
            : PdfCommandUtilities.ResolvePath(this, path!);
    }
}
