param(
    [string] $SmtpServer = 'smtp.example.com',
    [string] $From = 'reports@example.com',
    [string] $To = 'operations@example.com',
    [string] $OutputPath = '.\Daily-Service-Report.pdf',
    [switch] $Send
)

Import-Module PSWriteOffice -ErrorAction Stop
Import-Module Mailozaurr -ErrorAction Stop

$services = @(
    [pscustomobject]@{ Service = 'Directory'; Status = 'Healthy'; Incidents = 0 }
    [pscustomobject]@{ Service = 'Messaging'; Status = 'Attention'; Incidents = 2 }
    [pscustomobject]@{ Service = 'Database'; Status = 'Healthy'; Incidents = 0 }
)

New-OfficePdf -Path $OutputPath -Content {
    Add-OfficePdfHeading -Text 'Daily service report'
    Add-OfficePdfParagraph -Text "Generated $((Get-Date).ToString('u'))"
    Add-OfficePdfTable -InputObject $services
}

$mail = @{
    From       = $From
    To         = $To
    Subject    = 'Daily service report'
    Body       = 'The report generated by PSWriteOffice is attached.'
    SmtpServer = $SmtpServer
    Attachment = $OutputPath
    WhatIf     = -not $Send
}

Send-EmailMessage @mail
