BeforeAll {
    $ModuleManifest = if ($env:PSWRITEOFFICE_MODULE_MANIFEST) {
        $env:PSWRITEOFFICE_MODULE_MANIFEST
    } else {
        Join-Path $PSScriptRoot '..\PSWriteOffice.psd1'
    }
    Import-Module $ModuleManifest -Force -Global
}

Describe 'Markdown cmdlets' {
    It 'parses Markdown text into a document' {
        $doc = Get-OfficeMarkdown -Text "# Title`n`nHello"
        $doc | Should -BeOfType OfficeIMO.Markdown.MarkdownDoc
    }

    It 'supports reader profiles when parsing Markdown' {
        $doc = Get-OfficeMarkdown -Text "---`ntitle: Test`n---`n# Title" -Profile CommonMark
        $doc.HasDocumentHeader | Should -BeFalse
    }

    It 'converts objects to Markdown tables' {
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        $markdown = $rows | ConvertTo-OfficeMarkdown
        $markdown | Should -Match 'Name'
        $markdown | Should -Match 'Value'
    }

    It 'converts Markdown to HTML' {
        $html = ConvertTo-OfficeMarkdownHtml -Text "# Title`n`nHello"
        $html | Should -Match '<h1'
        $html | Should -Match 'Title'
    }

    It 'builds Markdown via DSL helpers' {
        $path = Join-Path $TestDrive 'MarkdownDsl.md'
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        $file = New-OfficeMarkdown -Path $path {
            MarkdownHeading -Level 1 -Text 'Report'
            MarkdownParagraph -Text 'Generated by PSWriteOffice'
            MarkdownList -Items 'One','Two'
            MarkdownTable -InputObject $rows
            MarkdownCode -Language 'powershell' -Content 'Get-Process'
            MarkdownHorizontalRule
        } -PassThru

        $file | Should -BeOfType System.IO.FileInfo
        $content = Get-Content -Path $path -Raw
        $content | Should -Match '# Report'
        $content | Should -Match 'Generated by PSWriteOffice'
        $content | Should -Match 'Name'
        $content | Should -Match 'Value'
    }

    It 'builds advanced Markdown blocks via DSL helpers' {
        $path = Join-Path $TestDrive 'MarkdownAdvancedDsl.md'

        New-OfficeMarkdown -Path $path {
            MarkdownFrontMatter -Data @{
                title = 'Operations Report'
                tags  = @('ops', 'weekly')
            }
            MarkdownTableOfContents -Title 'Contents' -PlaceAtTop -MinLevel 2 -MaxLevel 3
            MarkdownHeading -Level 1 -Text 'Operations Report'
            MarkdownHeading -Level 2 -Text 'Checklist'
            MarkdownTaskList -Items 'Draft', 'Review', 'Ship' -Completed 1
            MarkdownHeading -Level 2 -Text 'Glossary'
            MarkdownDefinitionList -Definition @{
                SLA = 'Service level agreement'
                SLO = 'Service level objective'
            }
            MarkdownDetails -Summary 'Implementation Notes' {
                MarkdownParagraph -Text 'Hidden by default.'
                MarkdownList -Items 'Thin wrapper', 'Powered by OfficeIMO'
            }
        } | Out-Null

        $content = Get-Content -Path $path -Raw
        $content | Should -Match 'title: "?Operations Report"?'
        $content | Should -Match '## Contents'
        $content | Should -Match '- \[ \] Draft'
        $content | Should -Match '- \[x\] Review'
        $content | Should -Match 'SLA'
        $content | Should -Match '<details>'
    }

    It 'supports advanced Markdown cmdlets against document objects' {
        $doc = [OfficeIMO.Markdown.MarkdownDoc]::Create()

        $doc |
            Add-OfficeMarkdownFrontMatter -Data @{ title = 'Doc pipeline' } -PassThru |
            Add-OfficeMarkdownHeading -Level 1 -Text 'Doc pipeline' -PassThru |
            Add-OfficeMarkdownTaskList -Items 'Alpha', 'Beta' -Completed 0 -PassThru |
            Add-OfficeMarkdownDefinitionList -Definition @{ API = 'Application programming interface' } -PassThru |
            Add-OfficeMarkdownDetails -Summary 'More' { MarkdownParagraph -Text 'Nested block' } |
            Out-Null

        $markdown = $doc.ToMarkdown()
        $markdown | Should -Match 'title: "?Doc pipeline"?'
        $markdown | Should -Match '- \[x\] Alpha'
        $markdown | Should -Match 'API'
        $markdown | Should -Match '<details>'
    }
}
