BeforeAll {
    $ModuleManifest = if ($env:PSWRITEOFFICE_MODULE_MANIFEST) {
        $env:PSWRITEOFFICE_MODULE_MANIFEST
    } else {
        Join-Path $PSScriptRoot '..\PSWriteOffice.psd1'
    }
    Import-Module $ModuleManifest -Force -Global
}

Describe 'Markdown cmdlets' {
    It 'parses Markdown text into a document' {
        $doc = Get-OfficeMarkdown -Text "# Title`n`nHello"
        $doc | Should -BeOfType OfficeIMO.Markdown.MarkdownDoc
    }

    It 'converts objects to Markdown tables' {
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        $markdown = $rows | ConvertTo-OfficeMarkdown
        $markdown | Should -Match 'Name'
        $markdown | Should -Match 'Value'
    }

    It 'converts Markdown to HTML' {
        $html = ConvertTo-OfficeMarkdownHtml -Text "# Title`n`nHello"
        $html | Should -Match '<h1'
        $html | Should -Match 'Title'
    }

    It 'builds Markdown via DSL helpers' {
        $path = Join-Path $TestDrive 'MarkdownDsl.md'
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        $file = New-OfficeMarkdown -Path $path {
            MarkdownHeading -Level 1 -Text 'Report'
            MarkdownParagraph -Text 'Generated by PSWriteOffice'
            MarkdownList -Items 'One','Two'
            MarkdownTable -InputObject $rows
            MarkdownCode -Language 'powershell' -Content 'Get-Process'
            MarkdownHorizontalRule
        } -PassThru

        $file | Should -BeOfType System.IO.FileInfo
        $content = Get-Content -Path $path -Raw
        $content | Should -Match '# Report'
        $content | Should -Match 'Generated by PSWriteOffice'
        $content | Should -Match 'Name'
        $content | Should -Match 'Value'
    }
}
