BeforeAll {
    $ModuleManifest = if ($env:PSWRITEOFFICE_MODULE_MANIFEST) {
        $env:PSWRITEOFFICE_MODULE_MANIFEST
    } else {
        Join-Path $PSScriptRoot '..\PSWriteOffice.psd1'
    }
    Import-Module $ModuleManifest -Global -ErrorAction Stop
}

Describe 'Office document PDF sidecar exports' {
    It 'creates native documents and PDF sidecars in one command' {
        $wordPath = Join-Path $TestDrive 'new-word.docx'
        $wordPdf = Join-Path $TestDrive 'new-word.pdf'
        New-OfficeWord -Path $wordPath -PdfPath $wordPdf {
            WordSection {
                WordParagraph -Text 'New Word PDF sidecar'
            }
        } | Out-Null

        $excelPath = Join-Path $TestDrive 'new-excel.xlsx'
        $excelPdf = Join-Path $TestDrive 'new-excel.pdf'
        New-OfficeExcel -Path $excelPath -PdfPath $excelPdf {
            ExcelSheet 'Data' {
                ExcelCell -Address 'A1' -Value 'New Excel PDF sidecar'
            }
        } | Out-Null

        $markdownPath = Join-Path $TestDrive 'new-markdown.md'
        $markdownPdf = Join-Path $TestDrive 'new-markdown.pdf'
        New-OfficeMarkdown -Path $markdownPath -PdfPath $markdownPdf {
            MarkdownHeading -Level 1 -Text 'New Markdown PDF sidecar'
        } | Out-Null

        $powerPointPath = Join-Path $TestDrive 'new-powerpoint.pptx'
        $powerPointPdf = Join-Path $TestDrive 'new-powerpoint.pdf'
        New-OfficePowerPoint -Path $powerPointPath -PdfPath $powerPointPdf {
            PptSlide {
                PptTitle -Title 'New PowerPoint PDF sidecar'
            }
        } | Out-Null

        foreach ($path in @($wordPath, $wordPdf, $excelPath, $excelPdf, $markdownPath, $markdownPdf, $powerPointPath, $powerPointPdf)) {
            Test-Path $path | Should -BeTrue
        }

        foreach ($path in @($wordPdf, $excelPdf, $markdownPdf, $powerPointPdf)) {
            (Get-OfficePdfPreflight -Path $path).CanRead | Should -BeTrue
        }
    }

    It 'saves Word documents with a PDF sidecar' {
        $docx = Join-Path $TestDrive 'word-report.docx'
        $pdf = Join-Path $TestDrive 'word-report.pdf'

        New-OfficeWord -Path $docx {
            WordSection {
                WordParagraph -Text 'Word PDF export smoke'
            }
        } | Out-Null

        $document = Get-OfficeWord -Path $docx
        try {
            $document | Save-OfficeWord -PdfPath $pdf | Out-Null
        } finally {
            Close-OfficeWord -Document $document
        }

        Test-Path $docx | Should -BeTrue
        Test-Path $pdf | Should -BeTrue
        (Get-OfficePdfPreflight -Path $pdf).CanRead | Should -BeTrue
        Get-OfficePdfText -Path $pdf | Should -Match 'Word PDF export smoke'
    }

    It 'saves Excel workbooks with a PDF sidecar' {
        $xlsx = Join-Path $TestDrive 'excel-report.xlsx'
        $pdf = Join-Path $TestDrive 'excel-report.pdf'

        New-OfficeExcel -Path $xlsx {
            ExcelSheet 'Data' {
                ExcelCell -Address 'A1' -Value 'Excel PDF export smoke'
                ExcelCell -Address 'B1' -Value 42
            }
        } | Out-Null

        $workbook = Get-OfficeExcel -Path $xlsx
        try {
            $workbook | Save-OfficeExcel -PdfPath $pdf | Out-Null
        } finally {
            Close-OfficeExcel -Document $workbook
        }

        Test-Path $xlsx | Should -BeTrue
        Test-Path $pdf | Should -BeTrue
        (Get-OfficePdfPreflight -Path $pdf).CanRead | Should -BeTrue
        Get-OfficePdfText -Path $pdf | Should -Match 'Excel PDF export smoke'
    }

    It 'saves Markdown documents with a PDF sidecar' {
        $md = Join-Path $TestDrive 'markdown-report.md'
        $pdf = Join-Path $TestDrive 'markdown-report.pdf'
        $document = Get-OfficeMarkdown -Text "# Markdown PDF export smoke`n`nGenerated by PSWriteOffice."

        $document | Save-OfficeMarkdown -Path $md -PdfPath $pdf | Out-Null

        Test-Path $md | Should -BeTrue
        Test-Path $pdf | Should -BeTrue
        (Get-OfficePdfPreflight -Path $pdf).CanRead | Should -BeTrue
        Get-OfficePdfText -Path $pdf | Should -Match 'Markdown PDF export smoke'
    }

    It 'saves PowerPoint presentations with a PDF sidecar' {
        $pptx = Join-Path $TestDrive 'deck-report.pptx'
        $pdf = Join-Path $TestDrive 'deck-report.pdf'

        New-OfficePowerPoint -Path $pptx {
            PptSlide {
                PptTitle -Title 'PowerPoint PDF export smoke'
            }
        } | Out-Null

        $presentation = Get-OfficePowerPoint -FilePath $pptx
        Save-OfficePowerPoint -Presentation $presentation -PdfPath $pdf | Out-Null

        Test-Path $pptx | Should -BeTrue
        Test-Path $pdf | Should -BeTrue
        $info = Get-OfficePdfInfo -Path $pdf
        $info.PageCount | Should -BeGreaterOrEqual 1
        (Get-OfficePdfPreflight -Path $pdf).CanRead | Should -BeTrue
    }
}
