BeforeAll {
    $ModuleManifest = if ($env:PSWRITEOFFICE_MODULE_MANIFEST) {
        $env:PSWRITEOFFICE_MODULE_MANIFEST
    } else {
        Join-Path $PSScriptRoot '..\PSWriteOffice.psd1'
    }
    Import-Module $ModuleManifest -Global -ErrorAction Stop
}

Describe 'PDF cmdlets' {
    It 'builds a composed PDF and extracts text' {
        $path = Join-Path $TestDrive 'report.pdf'
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        $file = New-OfficePdf -Path $path {
            PdfMetadata -Title 'Operations Report' -Author 'PSWriteOffice'
            PdfPageSetup -PageSize A4 -Margin 54
            PdfHeader 'Operations Report'
            PdfFooter 'Page {page}/{pages}'
            PdfHeading 'Operations Report'
            PdfParagraph 'Generated by PSWriteOffice'
            PdfPanel 'This is a visually separated note.'
            PdfList -Items 'Draft', 'Review', 'Ship' -Numbered
            PdfTable -InputObject $rows
            PdfPageBreak
            PdfHeading -Level 2 -Text 'Details'
            PdfParagraph 'Second page content'
        } -PassThru

        $file | Should -BeOfType System.IO.FileInfo
        Test-Path $path | Should -BeTrue

        $info = Get-OfficePdfInfo -Path $path
        $info.PageCount | Should -BeGreaterOrEqual 1

        $preflight = Get-OfficePdfPreflight -Path $path
        $preflight.CanRead | Should -BeTrue

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Operations Report'
        $text | Should -Match 'Generated by PSWriteOffice'
    }

    It 'renders hashtable rows using their dictionary values' {
        $path = Join-Path $TestDrive 'hashtable-table.pdf'
        $rows = @(
            @{ Name = 'Alpha'; Value = 1 }
            @{ Name = 'Beta'; Value = 2 }
        )

        New-OfficePdf -Path $path {
            PdfTable -InputObject $rows -Property Name, Value
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Alpha'
        $text | Should -Match '1'
        $text | Should -Match 'Beta'
        $text | Should -Match '2'
    }

    It 'renders multiple row arrays as table rows' {
        $path = Join-Path $TestDrive 'array-row-table.pdf'

        New-OfficePdf -Path $path {
            PdfTable -InputObject @(
                @('Name', 'Value'),
                @('Alpha', 1),
                @('Beta', 2)
            )
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Name'
        $text | Should -Match 'Alpha'
        $text | Should -Match 'Beta'
    }

    It 'renders explicit headers for array row tables' {
        $path = Join-Path $TestDrive 'array-row-table-header.pdf'

        New-OfficePdf -Path $path {
            PdfTable -Header Name, Value -InputObject @(
                @('Alpha', 1),
                @('Beta', 2)
            )
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Name'
        $text | Should -Match 'Value'
        $text | Should -Match 'Alpha'
        $text | Should -Match 'Beta'
    }

    It 'supports transposed table views' {
        $path = Join-Path $TestDrive 'transposed-table.pdf'
        $rows = @(
            [pscustomobject]@{ Name = 'Alpha'; Value = 1 }
            [pscustomobject]@{ Name = 'Beta'; Value = 2 }
        )

        New-OfficePdf -Path $path {
            PdfTable -InputObject $rows -View Transpose
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Property'
        $text | Should -Match 'Row1'
        $text | Should -Match 'Alpha'
        $text | Should -Match 'Beta'
    }

    It 'keeps the current page size when only margins are updated' {
        $path = Join-Path $TestDrive 'page-size-margin.pdf'

        New-OfficePdf -Path $path {
            PdfPageSetup -PageSize A4
            PdfPageSetup -Margin 36
            PdfHeading 'A4 report'
        } | Out-Null

        $page = (Get-OfficePdfInfo -Path $path).Pages[0]
        [math]::Round($page.Width) | Should -Be 595
        [math]::Round($page.Height) | Should -Be 842
    }

    It 'supports PDF page operations with approved verbs' {
        $path = Join-Path $TestDrive 'pages.pdf'
        New-OfficePdf -Path $path {
            PdfHeading 'Page 1'
            PdfPageBreak
            PdfHeading 'Page 2'
        } | Out-Null

        $rotated = Join-Path $TestDrive 'rotated.pdf'
        $copy = Join-Path $TestDrive 'copy.pdf'
        $removed = Join-Path $TestDrive 'removed.pdf'

        Set-OfficePdfPage -Path $path -Rotation 90 -OutputPath $rotated | Should -BeOfType System.IO.FileInfo
        Copy-OfficePdfPage -Path $path -PageRange '1' -OutputPath $copy | Should -BeOfType System.IO.FileInfo
        Remove-OfficePdfPage -Path $path -PageRange '2' -OutputPath $removed | Should -BeOfType System.IO.FileInfo

        (Get-OfficePdfInfo -Path $copy).PageCount | Should -Be 1
        (Get-OfficePdfInfo -Path $removed).PageCount | Should -Be 1
    }

    It 'creates PDFs with document-level font options' {
        $path = Join-Path $TestDrive 'font-options.pdf'
        New-OfficePdf -Path $path -DefaultFont Courier -DefaultFontSize 13 {
            PdfHeading 'Font Options'
            PdfParagraph 'Generated with document-level font settings.'
        } | Out-Null

        (Get-OfficePdfPreflight -Path $path).CanRead | Should -BeTrue
        Get-OfficePdfText -Path $path | Should -Match 'Font Options'
    }

    It 'builds visually polished PDF documents' {
        $path = Join-Path $TestDrive 'visual-polish.pdf'
        New-OfficePdf -Path $path {
            PdfBackground -Color '#F8FAFC'
            PdfPageBorder -Color '#0F766E' -Width 1.5 -Inset 24 -Opacity 0.85
            PdfBookmark 'summary'
            PdfHeading 'Visual Summary'
            PdfHr -Color '#0F766E' -Thickness 2 -SpacingBefore 8 -SpacingAfter 10
            PdfPanel 'A polished report surface should support visual structure.'
        } | Out-Null

        $info = Get-OfficePdfInfo -Path $path
        $info.PageCount | Should -Be 1
        $info.HasNamedDestinations | Should -BeTrue
        $info.NamedDestinationNames | Should -Contain 'summary'

        (Get-OfficePdfPreflight -Path $path).CanRead | Should -BeTrue
        Get-OfficePdfText -Path $path | Should -Match 'Visual Summary'
    }

    It 'builds two-column PDF layout rows' {
        $path = Join-Path $TestDrive 'layout-row.pdf'
        $rows = @(
            [pscustomobject]@{ Area = 'Coverage'; Status = 'Good' }
            [pscustomobject]@{ Area = 'Readback'; Status = 'Verified' }
        )

        New-OfficePdf -Path $path {
            PdfHeading 'Layout Report'
            PdfSpacer 10
            PdfRow -Gap 16 -SpacingBefore 4 -SpacingAfter 8 -ColumnSeparatorColor '#CBD5E1' -Column @(
                @{
                    Width = 38
                    Content = @(
                        @{ Type = 'Heading'; Level = 2; Text = 'Highlights'; HeadingColor = '#0F766E' }
                        @{ Type = 'Paragraph'; Text = 'Left column summary.' }
                        @{ Type = 'List'; Items = @('Designed surface', 'Readable rhythm'); Numbered = $true }
                    )
                }
                @{
                    Width = 62
                    Content = @(
                        @{ Type = 'Bookmark'; Name = 'layout-row' }
                        @{ Type = 'Panel'; Text = 'Right column panel.' }
                        @{ Type = 'Table'; InputObject = $rows }
                        @{ Type = 'Rule'; Color = '#0F766E'; Thickness = 1.2 }
                    )
                }
            )
            PdfParagraph 'After layout row.'
        } | Out-Null

        $info = Get-OfficePdfInfo -Path $path
        $info.PageCount | Should -Be 1
        $info.NamedDestinationNames | Should -Contain 'layout-row'

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Highlights'
        $text | Should -Match 'Right column panel'
        $text | Should -Match 'After layout row'
    }

    It 'renders typed list content directly inside PDF row columns' {
        $path = Join-Path $TestDrive 'layout-row-list.pdf'
        New-OfficePdf -Path $path {
            PdfRow -Column @(
                @{
                    Width = 100
                    Type = 'List'
                    Items = @('Alpha', 'Beta')
                }
            )
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Alpha'
        $text | Should -Match 'Beta'
    }

    It 'renders a single hashtable content block inside PDF row columns' {
        $path = Join-Path $TestDrive 'layout-row-single-content.pdf'
        New-OfficePdf -Path $path {
            PdfRow -Column @(
                @{
                    Width = 100
                    Content = @{
                        Type = 'Paragraph'
                        Text = 'Single content block'
                    }
                }
            )
        } | Out-Null

        Get-OfficePdfText -Path $path | Should -Match 'Single content block'
    }

    It 'renders a single table object inside PDF row columns' {
        $path = Join-Path $TestDrive 'layout-row-single-table-object.pdf'
        New-OfficePdf -Path $path {
            PdfRow -Column @(
                @{
                    Width = 100
                    Content = @(
                        @{
                            Type = 'Table'
                            InputObject = @{ Name = 'Alpha'; Value = 1 }
                            Header = @('Name', 'Value')
                        }
                    )
                }
            )
        } | Out-Null

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Name'
        $text | Should -Match 'Value'
        $text | Should -Match 'Alpha'
        $text | Should -Match '1'
    }

    It 'renders a single hashtable rich-text run inside PDF row columns' {
        $path = Join-Path $TestDrive 'layout-row-rich-run.pdf'
        New-OfficePdf -Path $path {
            PdfRow -Column @(
                @{
                    Width = 100
                    Content = @(
                        @{
                            Type = 'Paragraph'
                            Run = @{
                                Text = 'Approved'
                                Bold = $true
                            }
                        }
                    )
                }
            )
        } | Out-Null

        Get-OfficePdfText -Path $path | Should -Match 'Approved'
    }

    It 'builds rich PDF text with emphasis and links' {
        $path = Join-Path $TestDrive 'rich-text.pdf'
        New-OfficePdf -Path $path {
            PdfBookmark 'details'
            PdfText -Run @(
                @{ Text = 'This paragraph contains ' }
                @{ Text = 'bold'; Bold = $true; Color = '#0F766E' }
                @{ Text = ', ' }
                @{ Text = 'italic'; Italic = $true }
                @{ Text = ', highlighted '; BackgroundColor = '#FEF3C7' }
                @{ Text = 'external link'; LinkUri = 'https://evotec.xyz'; Color = '#2563EB' }
                @{ Text = ', and ' }
                @{ Text = 'bookmark link'; LinkDestinationName = 'details'; Color = '#7C3AED' }
                @{ Text = '.' }
            )
            PdfRow -Column @(
                @{
                    Width = 100
                    Content = @(
                        @{
                            Type = 'Paragraph'
                            Run = @(
                                @{ Text = 'Row layout can also contain ' }
                                @{ Text = 'rich inline text'; Bold = $true; LinkDestinationName = 'details'; Color = '#0F766E' }
                                @{ Text = '.' }
                            )
                        }
                    )
                }
            )
        } | Out-Null

        $info = Get-OfficePdfInfo -Path $path
        $info.HasLinkAnnotations | Should -BeTrue
        $info.LinkUris | Should -Contain 'https://evotec.xyz'
        $info.LinkDestinationNames | Should -Contain 'details'

        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'bold'
        $text | Should -Match 'bookmark link'
        $text | Should -Match 'rich inline text'
    }

    It 'applies PDF themes and decorative backgrounds' {
        $path = Join-Path $TestDrive 'styled-backgrounds.pdf'
        $imagePath = Join-Path $TestDrive 'pixel.png'
        [IO.File]::WriteAllBytes(
            $imagePath,
            [Convert]::FromBase64String('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg=='))

        New-OfficePdf -Path $path {
            PdfTheme Report
            PdfBackground -Color '#FFFFFF'
            PdfBackgroundImage -Path $imagePath -Fit Cover -Opacity 0.03
            PdfBackgroundShape -Shape TopBand -Height 86 -FillColor '#DBEAFE' -FillOpacity 0.75
            PdfBackgroundShape -Shape Ellipse -X 420 -Y 650 -Width 96 -Height 72 -FillColor '#99F6E4' -FillOpacity 0.35
            PdfHeading 'Styled Report'
            PdfParagraph 'Theme and decorative backgrounds are OfficeIMO-owned PDF layout features.'
            PdfPanel 'A reusable theme keeps report rhythm consistent.'
        } | Out-Null

        (Get-OfficePdfPreflight -Path $path).CanRead | Should -BeTrue
        $text = Get-OfficePdfText -Path $path
        $text | Should -Match 'Styled Report'
        $text | Should -Match 'reusable theme'
    }
}
