using System;
using System.Management.Automation;
using OfficeIMO.PowerPoint;
using PSWriteOffice.Services.PowerPoint;

namespace PSWriteOffice.Cmdlets.PowerPoint;

/// <summary>Adds a text box to a slide.</summary>
/// <para>Creates a rectangle at the requested coordinates and assigns the supplied text.</para>
/// <example>
///   <summary>Insert a caption.</summary>
///   <prefix>PS&gt; </prefix>
///   <code>New-OfficePowerPoint -Path .\Examples\Documents\PowerPointTextBox.pptx {
///     $slide = Add-OfficePowerPointSlide -Layout 1
///     Add-OfficePowerPointTextBox -Slide $slide -Text 'Quarterly overview' -X 80 -Y 150 -Width 320 -Height 50
///     Add-OfficePowerPointTextBox -Slide $slide -Text 'Generated by PSWriteOffice' -X 80 -Y 210 -Width 320 -Height 35
/// }</code>
///   <para>Places two text boxes on a generated slide.</para>
/// </example>
[Cmdlet(VerbsCommon.Add, "OfficePowerPointTextBox", DefaultParameterSetName = "Text")]
[Alias("PptTextBox")]
public class AddOfficePowerPointTextBoxCommand : PSCmdlet
{
    private const string ParameterSetText = "Text";
    private const string ParameterSetRun = "Run";

    /// <summary>Target slide that will receive the text box (optional inside DSL).</summary>
    [Parameter(ValueFromPipeline = true)]
    public PowerPointSlide? Slide { get; set; }

    /// <summary>Text to render inside the box.</summary>
    [Parameter(Mandatory = true, ParameterSetName = ParameterSetText)]
    public string? Text { get; set; }

    /// <summary>Rich text runs. Each run can be created with TextRun/PowerPointTextRun or provided as a hashtable/object.</summary>
    [Parameter(Mandatory = true, ParameterSetName = ParameterSetRun)]
    [Alias("Runs")]
    public object[]? Run { get; set; }

    /// <summary>Left offset (in points) from the slide origin.</summary>
    [Parameter]
    public int X { get; set; } = 50;

    /// <summary>Top offset (in points) from the slide origin.</summary>
    [Parameter]
    public int Y { get; set; } = 50;

    /// <summary>Box width in points.</summary>
    [Parameter]
    public int Width { get; set; } = 200;

    /// <summary>Box height in points.</summary>
    [Parameter]
    public int Height { get; set; } = 50;

    /// <inheritdoc />
    protected override void ProcessRecord()
    {
        try
        {
            var slide = Slide ?? PowerPointDslContext.Require(this).RequireSlide();
            var textBox = slide.AddTextBoxPoints(Text ?? string.Empty, X, Y, Width, Height);
            if (ParameterSetName == ParameterSetRun)
            {
                PowerPointTextRunService.ApplyRuns(textBox, Run!);
            }

            WriteObject(textBox);
        }
        catch (Exception ex)
        {
            WriteError(new ErrorRecord(ex, "PowerPointAddTextBoxFailed", ErrorCategory.InvalidOperation, Slide));
        }
    }
}
