$ErrorActionPreference = 'Stop'

Import-Module PSWriteOffice -ErrorAction Stop

$documents = Join-Path $PSScriptRoot '..\Documents'
$splitDirectory = Join-Path $documents 'Example-PdfOperations-Split'
$null = New-Item -Path $documents -ItemType Directory -Force
Remove-Item -Path $splitDirectory -Recurse -Force -ErrorAction SilentlyContinue

$first = Join-Path $documents 'Example-PdfOperations-A.pdf'
$second = Join-Path $documents 'Example-PdfOperations-B.pdf'
$joined = Join-Path $documents 'Example-PdfOperations-Joined.pdf'
$rotated = Join-Path $documents 'Example-PdfOperations-Rotated.pdf'
$metadata = Join-Path $documents 'Example-PdfOperations-Metadata.pdf'
$stamped = Join-Path $documents 'Example-PdfOperations-Stamped.pdf'

New-OfficePdf -Path $first {
    PdfHeading 'Operations Part A'
    PdfParagraph 'This source PDF is generated by PSWriteOffice.'
}

New-OfficePdf -Path $second {
    PdfHeading 'Operations Part B'
    PdfParagraph 'This second PDF will be joined, split, rotated, stamped, and inspected.'
}

Join-OfficePdf -Path $first, $second -OutputPath $joined
Split-OfficePdf -Path $joined -OutputDirectory $splitDirectory -Prefix 'part'
Set-OfficePdfPage -Path $joined -Rotation 90 -PageRange '2' -OutputPath $rotated
Set-OfficePdfMetadata -Path $rotated -OutputPath $metadata -Title 'PDF Operations Example' -Author 'PSWriteOffice' -Subject 'Existing PDF operations'
Add-OfficePdfStamp -Path $metadata -OutputPath $stamped -Text 'REVIEWED' -Color '#0F766E' -FontSize 22 -Rotation 12 -PageRange '1'

$markdown = ConvertTo-OfficePdfMarkdown -Path $stamped
$info = Get-OfficePdfInfo -Path $stamped

[pscustomobject]@{
    Path          = $stamped
    Pages         = $info.PageCount
    SplitFiles    = @(Get-ChildItem -LiteralPath $splitDirectory -Filter '*.pdf').Count
    MarkdownLines = @($markdown -split [Environment]::NewLine).Count
} | Format-List
