$ErrorActionPreference = 'Stop'

$modulePath = if ($env:PSWRITEOFFICE_MODULE_MANIFEST) {
    $env:PSWRITEOFFICE_MODULE_MANIFEST
} else {
    Join-Path $PSScriptRoot '..\..\PSWriteOffice.psd1'
}

if (-not (Get-Module -Name PSWriteOffice)) {
    Import-Module $modulePath -ErrorAction Stop
}

$documents = Join-Path $PSScriptRoot '..\Documents'
$splitDirectory = Join-Path $documents 'Example-PdfOperations-Split'
New-Item -Path $documents -ItemType Directory -Force | Out-Null
Remove-Item -Path $splitDirectory -Recurse -Force -ErrorAction SilentlyContinue

$first = Join-Path $documents 'Example-PdfOperations-A.pdf'
$second = Join-Path $documents 'Example-PdfOperations-B.pdf'
$joined = Join-Path $documents 'Example-PdfOperations-Joined.pdf'
$rotated = Join-Path $documents 'Example-PdfOperations-Rotated.pdf'
$metadata = Join-Path $documents 'Example-PdfOperations-Metadata.pdf'
$stamped = Join-Path $documents 'Example-PdfOperations-Stamped.pdf'

New-OfficePdf -Path $first {
    PdfHeading 'Operations Part A'
    PdfParagraph 'This source PDF is generated by PSWriteOffice.'
} | Out-Null

New-OfficePdf -Path $second {
    PdfHeading 'Operations Part B'
    PdfParagraph 'This second PDF will be joined, split, rotated, stamped, and inspected.'
} | Out-Null

Join-OfficePdf -Path $first, $second -OutputPath $joined -PassThru | Out-Null
Split-OfficePdf -Path $joined -OutputDirectory $splitDirectory -Prefix 'part' | Out-Null
Set-OfficePdfPage -Path $joined -Rotation 90 -PageRange '2' -OutputPath $rotated | Out-Null
Set-OfficePdfMetadata -Path $rotated -OutputPath $metadata -Title 'PDF Operations Example' -Author 'PSWriteOffice' -Subject 'Existing PDF operations' | Out-Null
Add-OfficePdfStamp -Path $metadata -OutputPath $stamped -Text 'REVIEWED' -Color '#0F766E' -FontSize 22 -Rotation 12 -PageRange '1' | Out-Null

$markdown = ConvertTo-OfficePdfMarkdown -Path $stamped
$info = Get-OfficePdfInfo -Path $stamped

[pscustomobject]@{
    Path          = $stamped
    Pages         = $info.PageCount
    SplitFiles    = @(Get-ChildItem -LiteralPath $splitDirectory -Filter '*.pdf').Count
    MarkdownLines = @($markdown -split [Environment]::NewLine).Count
} | Format-List
