Import-Module (Join-Path $PSScriptRoot '..\..\PSWriteOffice.psd1') -Force

$documents = Join-Path $PSScriptRoot '..\Documents'
New-Item -Path $documents -ItemType Directory -Force | Out-Null

$data = @(
    [PSCustomObject]@{ Region = 'North America'; Revenue = 125000; Owner = 'Ada' }
    [PSCustomObject]@{ Region = 'EMEA'; Revenue = 98000; Owner = 'Linus' }
    [PSCustomObject]@{ Region = 'APAC'; Revenue = 143000; Owner = 'Grace' }
)

$path = Join-Path $documents 'Excel-TablesAndRanges.xlsx'
New-OfficeExcel -Path $path {
    ExcelSheet 'Summary' {
        Set-OfficeExcelRow -Row 1 -Values 'Region', 'Revenue', 'Owner'
        Add-OfficeExcelTable -Data $data -TableName 'Sales' -TableStyle 'TableStyleMedium9' -AutoFit
        Set-OfficeExcelNamedRange -Name 'Revenue' -Range 'B2:B4'
    }
    ExcelSheet 'Notes' {
        ExcelCell -Address 'A1' -Value 'Generated by PSWriteOffice'
    }
} | Out-Null

Write-Host "Workbook saved to $path"
Write-Host 'Tables:'
Get-OfficeExcelTable -Path $path | Format-Table